### ISSUE TITLE
installing viskit 

### ISSUE THREAD

**Issue by capybaralet** [tianheyu927/mopo#1]
This line of the installation instructions didn't work for me:
`pip install -e viskit`

Does this just mean that you should clone viskit somewhere else and install it with `pip install -e`?

e.g.
`cd ~`
`git clone git@github.com:vitchyr/viskit.git`
`cd viskit`
`pip install -e .`

**Comment by tianheyu927** [comment]
Yes, that's correct. I've updated the README with the new installation instruction.
